apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-01
  namespace: pai-gpu
spec:
    containers:
    - image: tensorflow:latest
      name: main
      resources:
        limits:
          cpu: 8
          memory: 17408Mi
        requests:
          cpu: 8
          memory: 17408Mi
