apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-02
  namespace: pai-gpu
  annotations:
    alibabacloud.com/gpu-milli: "1000"
    alibabacloud.com/gpu-count: "2"
spec:
    containers:
    - image: tensorflow:latest
      name: main
      resources:
        limits:
          cpu: 12
          memory: 18432Mi
        requests:
          cpu: 12
          memory: 18432Mi
